# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_management_serverStreaming.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&order_management_serverStreaming.proto\x12\x0fordermanagement\"\"\n\x0cOrderRequest\x12\x12\n\norder_name\x18\x01 \x01(\t\"5\n\rOrderResponse\x12\x11\n\titem_name\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\t\".\n\x16ReceiveMessagesRequest\x12\x14\n\x0cnum_messages\x18\x01 \x01(\x05\"+\n\x17ReceiveMessagesResponse\x12\x10\n\x08messages\x18\x01 \x03(\t2\xc8\x01\n\x0fOrderManagement\x12K\n\x08getOrder\x12\x1d.ordermanagement.OrderRequest\x1a\x1e.ordermanagement.OrderResponse\"\x00\x12h\n\x0freceiveMessages\x12\'.ordermanagement.ReceiveMessagesRequest\x1a(.ordermanagement.ReceiveMessagesResponse\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_management_serverStreaming_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ORDERREQUEST']._serialized_start=59
  _globals['_ORDERREQUEST']._serialized_end=93
  _globals['_ORDERRESPONSE']._serialized_start=95
  _globals['_ORDERRESPONSE']._serialized_end=148
  _globals['_RECEIVEMESSAGESREQUEST']._serialized_start=150
  _globals['_RECEIVEMESSAGESREQUEST']._serialized_end=196
  _globals['_RECEIVEMESSAGESRESPONSE']._serialized_start=198
  _globals['_RECEIVEMESSAGESRESPONSE']._serialized_end=241
  _globals['_ORDERMANAGEMENT']._serialized_start=244
  _globals['_ORDERMANAGEMENT']._serialized_end=444
# @@protoc_insertion_point(module_scope)
