# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_management_Unary.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1corder_management_Unary.proto\x12\x0fordermanagement\"\"\n\x0cOrderRequest\x12\x12\n\norder_name\x18\x01 \x01(\t\"5\n\rOrderResponse\x12\x11\n\titem_name\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\t2\xd4\x02\n\x0fOrderManagement\x12K\n\x08getOrder\x12\x1d.ordermanagement.OrderRequest\x1a\x1e.ordermanagement.OrderResponse\"\x00\x12O\n\x0csearchOrders\x12\x1d.ordermanagement.OrderRequest\x1a\x1e.ordermanagement.OrderResponse0\x01\x12O\n\x0cupdateOrders\x12\x1d.ordermanagement.OrderRequest\x1a\x1e.ordermanagement.OrderResponse(\x01\x12R\n\rprocessOrders\x12\x1d.ordermanagement.OrderRequest\x1a\x1e.ordermanagement.OrderResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_management_Unary_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ORDERREQUEST']._serialized_start=49
  _globals['_ORDERREQUEST']._serialized_end=83
  _globals['_ORDERRESPONSE']._serialized_start=85
  _globals['_ORDERRESPONSE']._serialized_end=138
  _globals['_ORDERMANAGEMENT']._serialized_start=141
  _globals['_ORDERMANAGEMENT']._serialized_end=481
# @@protoc_insertion_point(module_scope)
