# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import order_management_Unary_pb2 as order__management__Unary__pb2


class OrderManagementStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getOrder = channel.unary_unary(
                '/ordermanagement.OrderManagement/getOrder',
                request_serializer=order__management__Unary__pb2.OrderRequest.SerializeToString,
                response_deserializer=order__management__Unary__pb2.OrderResponse.FromString,
                )
        self.searchOrders = channel.unary_stream(
                '/ordermanagement.OrderManagement/searchOrders',
                request_serializer=order__management__Unary__pb2.OrderRequest.SerializeToString,
                response_deserializer=order__management__Unary__pb2.OrderResponse.FromString,
                )
        self.updateOrders = channel.stream_unary(
                '/ordermanagement.OrderManagement/updateOrders',
                request_serializer=order__management__Unary__pb2.OrderRequest.SerializeToString,
                response_deserializer=order__management__Unary__pb2.OrderResponse.FromString,
                )
        self.processOrders = channel.stream_stream(
                '/ordermanagement.OrderManagement/processOrders',
                request_serializer=order__management__Unary__pb2.OrderRequest.SerializeToString,
                response_deserializer=order__management__Unary__pb2.OrderResponse.FromString,
                )


class OrderManagementServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getOrder(self, request, context):
        """Unary
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def searchOrders(self, request, context):
        """Server Streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateOrders(self, request_iterator, context):
        """Client Streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def processOrders(self, request_iterator, context):
        """Both Streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderManagementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.getOrder,
                    request_deserializer=order__management__Unary__pb2.OrderRequest.FromString,
                    response_serializer=order__management__Unary__pb2.OrderResponse.SerializeToString,
            ),
            'searchOrders': grpc.unary_stream_rpc_method_handler(
                    servicer.searchOrders,
                    request_deserializer=order__management__Unary__pb2.OrderRequest.FromString,
                    response_serializer=order__management__Unary__pb2.OrderResponse.SerializeToString,
            ),
            'updateOrders': grpc.stream_unary_rpc_method_handler(
                    servicer.updateOrders,
                    request_deserializer=order__management__Unary__pb2.OrderRequest.FromString,
                    response_serializer=order__management__Unary__pb2.OrderResponse.SerializeToString,
            ),
            'processOrders': grpc.stream_stream_rpc_method_handler(
                    servicer.processOrders,
                    request_deserializer=order__management__Unary__pb2.OrderRequest.FromString,
                    response_serializer=order__management__Unary__pb2.OrderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ordermanagement.OrderManagement', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OrderManagement(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ordermanagement.OrderManagement/getOrder',
            order__management__Unary__pb2.OrderRequest.SerializeToString,
            order__management__Unary__pb2.OrderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def searchOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ordermanagement.OrderManagement/searchOrders',
            order__management__Unary__pb2.OrderRequest.SerializeToString,
            order__management__Unary__pb2.OrderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def updateOrders(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/ordermanagement.OrderManagement/updateOrders',
            order__management__Unary__pb2.OrderRequest.SerializeToString,
            order__management__Unary__pb2.OrderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def processOrders(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/ordermanagement.OrderManagement/processOrders',
            order__management__Unary__pb2.OrderRequest.SerializeToString,
            order__management__Unary__pb2.OrderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
